services:
  loadbalancer:
    build:
      context: .
      dockerfile: haproxy.Dockerfile
      args:
        HAPROXY_IMAGE: haproxy:2.2.20
    container_name: bb_loadbalancer
    ports:
      - 7990:80
      - 7999:7999
    networks:
      cluster:
        aliases:
          - localhost
    depends_on:
      - node1
      - node2
  database:
    image: postgres:11.14
    container_name: bb_database
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=bitbucket
      - POSTGRES_USER=bitbucket
      - POSTGRES_DB=bitbucket
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - cluster
  pgadmin:
    image: dpage/pgadmin4:6.2
    container_name: bb_pgadmin
    ports:
      - 5051:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=bitbucket@example.com
      - PGADMIN_DEFAULT_PASSWORD=bitbucket
      - PGADMIN_LISTEN_PORT=80
    networks:
      - cluster
  node1:
    build: bitbucket
    build:
      context: .
      dockerfile: bitbucket.Dockerfile
      args:
        BITBUCKET_IMAGE: atlassian/bitbucket:7.19.2
    container_name: bb_node1
    ports:
      - 7991:7990
      - 7998:7999
    environment:
      # Memory / Heap Size
      - JVM_MINIMUM_MEMORY=512M
      - JVM_MAXIMUM_MEMORY=2048M
      # Reverse Proxy Settings
      - SERVER_PROXY_NAME=localhost
      - SERVER_PROXY_PORT=7990
      # Application Mode Settings
      - ELASTICSEARCH_ENABLED=false
      # Database
      - JDBC_URL=jdbc:postgresql://database:5432/bitbucket
      - JDBC_USER=bitbucket
      - JDBC_PASSWORD=bitbucket
      - JDBC_DRIVER=org.postgresql.Driver
      # Data Center configuration
      - HAZELCAST_NETWORK_MULTICAST=true
      - HAZELCAST_PORT=5701
      - HAZELCAST_GROUP_NAME=bitbucket
      - HAZELCAST_GROUP_PASSWORD=bitbucket
        # - HAZELCAST_NETWORK_TCPIP=true
        # - HAZELCAST_NETWORK_TCPIP_MEMEBERS=10.0.0.8:5701,10.0.0.9:5701
      # Home Directories
      - BITBUCKET_HOME=/var/atlassian/application-data/bitbucket
      - BITBUCKET_SHARED_HOME=/var/atlassian/application-data/bitbucket/shared
      - PLUGIN_RESOURCE_DIRECTORIES=/var/atlassian/application-data/bitbucket/scripts
    volumes:
      - shared:/var/atlassian/application-data/bitbucket/shared
    depends_on:
      - database
    networks:
      - cluster
  node2:
    build: bitbucket
    build:
      context: .
      dockerfile: bitbucket.Dockerfile
      args:
        BITBUCKET_IMAGE: atlassian/bitbucket:7.19.2
    container_name: bb_node2
    ports:
      - 7992:7990
      - 7997:7999
    environment:
      # Memory / Heap Size
      - JVM_MINIMUM_MEMORY=512M
      - JVM_MAXIMUM_MEMORY=2048M
      # Reverse Proxy Settings
      - SERVER_PROXY_NAME=localhost
      - SERVER_PROXY_PORT=7990
      # Application Mode Settings
      - ELASTICSEARCH_ENABLED=false
      # Database
      - JDBC_URL=jdbc:postgresql://database:5432/bitbucket
      - JDBC_USER=bitbucket
      - JDBC_PASSWORD=bitbucket
      - JDBC_DRIVER=org.postgresql.Driver
      # Data Center configuration
      - HAZELCAST_NETWORK_MULTICAST=true
      - HAZELCAST_PORT=5701
      - HAZELCAST_GROUP_NAME=bitbucket
      - HAZELCAST_GROUP_PASSWORD=bitbucket
        # - HAZELCAST_NETWORK_TCPIP=true
        # - HAZELCAST_NETWORK_TCPIP_MEMEBERS=10.0.0.8:5701,10.0.0.9:5701
      # Home Directories
      - BITBUCKET_HOME=/var/atlassian/application-data/bitbucket
      - BITBUCKET_SHARED_HOME=/var/atlassian/application-data/bitbucket/shared
      - PLUGIN_RESOURCE_DIRECTORIES=/var/atlassian/application-data/bitbucket/scripts
    volumes:
      - shared:/var/atlassian/application-data/bitbucket/shared
    depends_on:
      - database
    networks:
      - cluster
volumes:
  database:
  shared:
networks:
  cluster:
