version: "3.7"
services:
  bitbucket-loadbalancer:
    build: haproxy
    container_name: bblb
    ports:
      - 7990:80
      - 7999:7999
    networks:
      cluster:
        ipv4_address: 10.0.0.5
        aliases:
          - localhost
  bitbucket-database:
    image: postgres:11.14
    container_name: bbdb
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=bitbucket
      - POSTGRES_USER=bitbucket
      - POSTGRES_DB=bitbucket
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      cluster:
        ipv4_address: 10.0.0.6
  bitbucket-pgadmin:
    image: dpage/pgadmin4:6.2
    container_name: bbpgadmin
    ports:
      - 5051:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=support@adaptavist.com
      - PGADMIN_DEFAULT_PASSWORD=bitbucket
      - PGADMIN_LISTEN_PORT=80
    networks:
      cluster:
        ipv4_address: 10.0.0.7
  bitbucket-node1:
    build: bitbucket
    container_name: bb1
    ports:
      - 7991:7990
      - 7998:7999
    environment:
      # Memory / Heap Size
      - JVM_MINIMUM_MEMORY=512M
      - JVM_MAXIMUM_MEMORY=2048M
      # Reverse Proxy Settings
      - SERVER_PROXY_NAME=localhost
      - SERVER_PROXY_PORT=7990
      # Application Mode Settings
      - ELASTICSEARCH_ENABLED=false
      # Database
      - JDBC_URL=jdbc:postgresql://10.0.0.6:5432/bitbucket
      - JDBC_USER=bitbucket
      - JDBC_PASSWORD=bitbucket
      - JDBC_DRIVER=org.postgresql.Driver
      # Data Center configuration
      - HAZELCAST_NETWORK_MULTICAST=true
      - HAZELCAST_PORT=5701
      - HAZELCAST_GROUP_NAME=bitbucket
      - HAZELCAST_GROUP_PASSWORD=bitbucket
        # - HAZELCAST_NETWORK_TCPIP=true
        # - HAZELCAST_NETWORK_TCPIP_MEMEBERS=10.0.0.8:5701,10.0.0.9:5701
      # Home Directories
      - BITBUCKET_HOME=/var/atlassian/application-data/bitbucket
      - BITBUCKET_SHARED_HOME=/var/atlassian/application-data/bitbucket/shared
    volumes:
      - shared:/var/atlassian/application-data/bitbucket/shared
    depends_on:
      - bbdb
    networks:
      cluster:
        ipv4_address: 10.0.0.8
  bitbucket-node2:
    build: bitbucket
    container_name: bb2
    ports:
      - 7992:7990
      - 7997:7999
    environment:
      # Memory / Heap Size
      - JVM_MINIMUM_MEMORY=512M
      - JVM_MAXIMUM_MEMORY=2048M
      # Reverse Proxy Settings
      - SERVER_PROXY_NAME=localhost
      - SERVER_PROXY_PORT=7990
      # Application Mode Settings
      - ELASTICSEARCH_ENABLED=false
      # Database
      - JDBC_URL=jdbc:postgresql://10.0.0.6:5432/bitbucket
      - JDBC_USER=bitbucket
      - JDBC_PASSWORD=bitbucket
      - JDBC_DRIVER=org.postgresql.Driver
      # Data Center configuration
      - HAZELCAST_NETWORK_MULTICAST=true
      - HAZELCAST_PORT=5701
      - HAZELCAST_GROUP_NAME=bitbucket
      - HAZELCAST_GROUP_PASSWORD=bitbucket
        # - HAZELCAST_NETWORK_TCPIP=true
        # - HAZELCAST_NETWORK_TCPIP_MEMEBERS=10.0.0.8:5701,10.0.0.9:5701
      # Home Directories
      - BITBUCKET_HOME=/var/atlassian/application-data/bitbucket
      - BITBUCKET_SHARED_HOME=/var/atlassian/application-data/bitbucket/shared
    volumes:
      - shared:/var/atlassian/application-data/bitbucket/shared
    depends_on:
      - bbdb
    networks:
      cluster:
        ipv4_address: 10.0.0.9
volumes:
  database:
  shared:
networks:
  cluster:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
