services:
  loadbalancer:
    build:
      context: .
      dockerfile: haproxy.Dockerfile
      args:
        HAPROXY_IMAGE: haproxy:2.2.20
    container_name: jira_loadbalancer
    ports:
      - 8080:443
    networks:
      cluster:
        aliases:
          - localhost
    depends_on:
      - node1
      - node2
  database:
    image: postgres:11.14
    container_name: jira_database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=jira
      - POSTGRES_USER=jira
      - POSTGRES_DB=jira
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - cluster
  pgadmin:
    image: dpage/pgadmin4:6.2
    container_name: jira_pgadmin
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=jira@example.com
      - PGADMIN_DEFAULT_PASSWORD=jira
      - PGADMIN_LISTEN_PORT=80
    networks:
      - cluster
  node1:
    build:
      context: .
      dockerfile: jira.Dockerfile
      args:
        JIRA_IMAGE: atlassian/jira-software:8.20.2
    container_name: jira_node1
    ports:
      - 8081:8080
    environment:
      # Memory / Heap Size
      - JVM_MINIMUM_MEMORY=512M
      - JVM_MAXIMUM_MEMORY=2048M
      # Reverse Proxy Settings
      - ATL_PROXY_NAME=localhost
      - ATL_PROXY_PORT=8080
      - ATL_TOMCAT_SCHEME=https
      - ATL_TOMCAT_SECURE=true
      # - ATL_TOMCAT_PROTOCOL=HTTP/2
      # Database
      - ATL_JDBC_URL=jdbc:postgresql://database:5432/jira
      - ATL_JDBC_USER=jira
      - ATL_JDBC_PASSWORD=jira
      - ATL_DB_DRIVER=org.postgresql.Driver
      - ATL_DB_TYPE=postgres72
      # Data Center configuration
      - CLUSTERED=true
      - JIRA_NODE_ID=jira1
      # Home Directories
      - JIRA_HOME=/var/atlassian/application-data/jira
      - JIRA_SHARED_HOME=/var/atlassian/application-data/shared
    volumes:
      - shared:/var/atlassian/application-data/shared
    depends_on:
      - database
    networks:
      - cluster
  node2:
    build:
      context: .
      dockerfile: jira.Dockerfile
      args:
        JIRA_IMAGE: atlassian/jira-software:8.20.2
    container_name: jira_node2
    ports:
      - 8082:8080
    environment:
      # Memory / Heap Size
      - JVM_MINIMUM_MEMORY=512M
      - JVM_MAXIMUM_MEMORY=2048M
      # Reverse Proxy Settings
      - ATL_PROXY_NAME=localhost
      - ATL_PROXY_PORT=8080
      - ATL_TOMCAT_SCHEME=https
      - ATL_TOMCAT_SECURE=true
      # - ATL_TOMCAT_PROTOCOL=HTTP/2
      # Database
      - ATL_JDBC_URL=jdbc:postgresql://database:5432/jira
      - ATL_JDBC_USER=jira
      - ATL_JDBC_PASSWORD=jira
      - ATL_DB_DRIVER=org.postgresql.Driver
      - ATL_DB_TYPE=postgres72
      # Data Center configuration
      - CLUSTERED=true
      - JIRA_NODE_ID=jira2
      # Home Directories
      - JIRA_HOME=/var/atlassian/application-data/jira
      - JIRA_SHARED_HOME=/var/atlassian/application-data/shared
    volumes:
      - shared:/var/atlassian/application-data/shared
    depends_on:
      - database
    networks:
      - cluster
volumes:
  database:
  shared:
networks:
  cluster:
