services:
  server:
    image: gists/nfs-server
    container_name: nfs-server
    ports:
      - 2049:2049
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    environment:
      - "NFS_OPTION=fsid=0,rw,sync,insecure,all_squash,anonuid=0,anongid=0,no_subtree_check,nohide"
    volumes:
      - mynfs:/mynfs
volumes:
  mynfs:
